/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import ConexionSQL.ConexionBD;
import Seminario1.Sistema;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mikel
 */
public class Interfaz extends javax.swing.JPanel {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        repaint();
        revalidate();
        cargarTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuAltaPedido = new javax.swing.JPanel();
        tituloAltaPedido = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoCodigoPedido = new javax.swing.JTextField();
        campoCodigoCliente = new javax.swing.JTextField();
        campoFechaPedido = new javax.swing.JTextField();
        tituloDetalles = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoCodigoProducto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoCantidadProducto = new javax.swing.JTextField();
        botonBorrarDetalles = new javax.swing.JButton();
        botonBorrarPedido = new javax.swing.JButton();
        botonTerminarPedido = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        botonCerrarSesión = new javax.swing.JButton();
        botonAnadirStock = new javax.swing.JButton();
        botonAltaPedido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaStock = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        tituloAltaPedido.setText("Dar de alta un pedido");

        jLabel4.setText("Código de Pedido:");

        jLabel5.setText("Código de cliente:");

        jLabel6.setText("Fecha del pedido:");

        campoCodigoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoPedidoActionPerformed(evt);
            }
        });

        tituloDetalles.setText("Añadir detalles(opcional)");

        jLabel8.setText("Código de Producto:");

        jLabel9.setText("Cantidad: ");

        botonBorrarDetalles.setText("Borrar detalles de pedido");
        botonBorrarDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarDetallesActionPerformed(evt);
            }
        });

        botonBorrarPedido.setText("Borrar pedido");
        botonBorrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarPedidoActionPerformed(evt);
            }
        });

        botonTerminarPedido.setText("Guardar pedido");
        botonTerminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTerminarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuAltaPedidoLayout = new javax.swing.GroupLayout(menuAltaPedido);
        menuAltaPedido.setLayout(menuAltaPedidoLayout);
        menuAltaPedidoLayout.setHorizontalGroup(
            menuAltaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuAltaPedidoLayout.createSequentialGroup()
                .addGroup(menuAltaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuAltaPedidoLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(tituloAltaPedido))
                    .addGroup(menuAltaPedidoLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(tituloDetalles)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuAltaPedidoLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(menuAltaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuAltaPedidoLayout.createSequentialGroup()
                        .addGroup(menuAltaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(menuAltaPedidoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(campoFechaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(menuAltaPedidoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(campoCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(menuAltaPedidoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(campoCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(menuAltaPedidoLayout.createSequentialGroup()
                                .addGroup(menuAltaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(menuAltaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoCodigoProducto)
                                    .addGroup(menuAltaPedidoLayout.createSequentialGroup()
                                        .addComponent(campoCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuAltaPedidoLayout.createSequentialGroup()
                                .addComponent(botonTerminarPedido)
                                .addGap(66, 66, 66)))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuAltaPedidoLayout.createSequentialGroup()
                        .addComponent(botonBorrarDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
            .addGroup(menuAltaPedidoLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(botonBorrarPedido)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menuAltaPedidoLayout.setVerticalGroup(
            menuAltaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuAltaPedidoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tituloAltaPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuAltaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuAltaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuAltaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoFechaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tituloDetalles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuAltaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuAltaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(campoCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(botonTerminarPedido)
                .addGap(18, 18, 18)
                .addComponent(botonBorrarDetalles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonBorrarPedido)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        titulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        titulo.setText("SISTEMA DE PEDIDOS");

        botonCerrarSesión.setBackground(new java.awt.Color(255, 204, 102));
        botonCerrarSesión.setForeground(new java.awt.Color(255, 255, 255));
        botonCerrarSesión.setText("Cerrar Sesión");
        botonCerrarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesiónActionPerformed(evt);
            }
        });

        botonAnadirStock.setText("Añadir Stock");
        botonAnadirStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnadirStockActionPerformed(evt);
            }
        });

        botonAltaPedido.setText("Dar de alta un nuevo pedido");
        botonAltaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAltaPedidoActionPerformed(evt);
            }
        });

        tablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código de pedido", "Cliente", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaPedidos);

        jLabel2.setText("Pedidos");

        jLabel3.setText("Stock");

        tablaStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código de Producto", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaStock);

        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código del pedido", "Código del producto", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaDetalle);

        jLabel1.setText("Detalles de los pedidos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(253, 253, 253)
                                .addComponent(botonCerrarSesión, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addComponent(jLabel2)))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonAnadirStock, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonAltaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(146, 146, 146)
                                        .addComponent(jLabel3))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(titulo)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAnadirStock)
                        .addGap(18, 18, 18)
                        .addComponent(botonAltaPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonCerrarSesión, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesiónActionPerformed
         //Añadir función para que cierre conexión con la BD
    }//GEN-LAST:event_botonCerrarSesiónActionPerformed

    private void botonAnadirStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAnadirStockActionPerformed

    private void botonAltaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAltaPedidoActionPerformed
        menuAltaPedido.setVisible(true);

        this.validate();
    }//GEN-LAST:event_botonAltaPedidoActionPerformed

    private void campoCodigoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoPedidoActionPerformed

    private void botonBorrarDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarDetallesActionPerformed
        campoCantidadProducto.setText(" ");
        campoCodigoProducto.setText(" ");
    }//GEN-LAST:event_botonBorrarDetallesActionPerformed
    
    
    private void cargarTablas(){
        DefaultTableModel modeloTablaPedidos = (DefaultTableModel)tablaPedidos.getModel();
        DefaultTableModel modeloTablaStock = (DefaultTableModel)tablaStock.getModel();
        DefaultTableModel modeloTablaDetalle = (DefaultTableModel)tablaDetalle.getModel();
        
        modeloTablaPedidos.setRowCount(0);
        
        PreparedStatement cn;
        ResultSet rs;
        ResultSetMetaData rsmd;
        
        int columnas;
        
        try{
            
            ConexionBD conexion = new ConexionSQL.ConexionBD();
            Connection con = conexion.conectar();
            cn = con.prepareStatement("SELECT CPEDIDO,CCLIENTE,FECHA_PEDIDO FROM PEDIDO");
            rs = cn.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for (int indice =0; indice < columnas; indice++){
                    fila[indice] = rs.getObject(indice + 1);
                }
                modeloTablaPedidos.addRow(fila);
            }
            
            cn = con.prepareStatement("SELECT CPRODUCTO,CANTIDAD FROM PEDIDO");
            rs = cn.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for (int indice =0; indice < columnas; indice++){
                    fila[indice] = rs.getObject(indice + 1);
                }
                modeloTablaStock.addRow(fila);
            }
            
            cn = con.prepareStatement("SELECT CPEDIDO,CPRODUCTO,CANTIDAD FROM DETALLE-PEDIDO");
            rs = cn.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for (int indice =0; indice < columnas; indice++){
                    fila[indice] = rs.getObject(indice + 1);
                }
                modeloTablaDetalle.addRow(fila);
            }
        }catch(SQLException e){
           JOptionPane.showMessageDialog(null, e.toString()); 
        }
    }
    
    private void botonTerminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTerminarPedidoActionPerformed
        int cpedido= Integer.parseInt(campoCodigoPedido.getText());
        int ccliente= Integer.parseInt(campoCodigoCliente.getText());
        String fecha = campoFechaPedido.getText();
        
        if(campoCantidadProducto.getText()!=null && campoCodigoProducto.getText()!=null){
            int cproducto= Integer.parseInt(campoCodigoProducto.getText());
            int cantidad= Integer.parseInt(campoCantidadProducto.getText());
        }
        
        try{
            ConexionBD conexion = new ConexionSQL.ConexionBD();
            Connection con = conexion.conectar();
            PreparedStatement cn = con.prepareStatement("INSERT INTO PEDIDO (CPEDIDO,CCLIENTE,FECHA_PEDIDO) VALUES(?,?,?)");
            
            cn.setInt(1,cpedido);
            cn.setInt(1,ccliente);
            cn.setString(1,fecha);
            
            cn.executeUpdate();
            
            campoCodigoPedido.setText(" ");
            campoCodigoCliente.setText(" ");
            campoFechaPedido.setText(" ");
            campoCantidadProducto.setText(" ");
            campoCodigoProducto.setText(" ");
            cargarTablas();
            menuAltaPedido.setVisible(false);
            
        }catch(SQLException e){
           JOptionPane.showMessageDialog(null, e.toString()); 
        }
        
        
    }//GEN-LAST:event_botonTerminarPedidoActionPerformed

    private void botonBorrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarPedidoActionPerformed
        campoCodigoPedido.setText(" ");
        campoCodigoCliente.setText(" ");
        campoFechaPedido.setText(" ");
        campoCantidadProducto.setText(" ");
        campoCodigoProducto.setText(" ");
        menuAltaPedido.setVisible(false);
    }//GEN-LAST:event_botonBorrarPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAltaPedido;
    private javax.swing.JButton botonAnadirStock;
    private javax.swing.JButton botonBorrarDetalles;
    private javax.swing.JButton botonBorrarPedido;
    private javax.swing.JButton botonCerrarSesión;
    private javax.swing.JButton botonTerminarPedido;
    private javax.swing.JTextField campoCantidadProducto;
    private javax.swing.JTextField campoCodigoCliente;
    private javax.swing.JTextField campoCodigoPedido;
    private javax.swing.JTextField campoCodigoProducto;
    private javax.swing.JTextField campoFechaPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel menuAltaPedido;
    private javax.swing.JTable tablaDetalle;
    private javax.swing.JTable tablaPedidos;
    private javax.swing.JTable tablaStock;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloAltaPedido;
    private javax.swing.JLabel tituloDetalles;
    // End of variables declaration//GEN-END:variables
}
